### PR TITLE
prep_void_rpi.sh may format the main drive in case of an inattention

### PR DESCRIPTION
**Pull request by efe3535**
So, I replaced /dev/sda as /dev/sdX to prevent that.

### CODE REVIEW

**Comment by kpa28-git** [comment]
Thanks for the PR! I appreciate it!
These scripts were a little too barebones. Setting to `/dev/sda` is a bad idea despite any written warning you give :) Should've done something else from the beginning, but I thought I was the only one using these

I pushed a change to have them use an env variable. If it isn't set, the script will warn the user and exit with error.

**Comment by kpa28-git** [comment]
For your second commit, looks like you're booting from sd. Should have made it clear that the script was for usb boot :) My bad

I changed the naming convention to make it more clear in the future. Now it's `setup_{bootmedia}.sh`. If you want to add `void/3bplus/setup_sd.sh` and PR it, please go right ahead. I'd do it but I don't have an sd card adaptor to test it.

Setup might be a little different, at minimum it looks like:

changing: `PI_VOID_3BPLUS_USB` -> `PI_VOID_3BPLUS_SD` (for convention)

adding your fstab change (should be `/dev/mmcblk0p1` for sd card)

removing these lines:
`
echo 'changing root partition from default...';
sed "s|/dev/mmcblk0p2|$PIPART2|" rootfs/boot/cmdline.txt | sudo tee rootfs/boot/cmdline.txt;
`

**Comment by kpa28-git** [comment]
Think this will work for `void/3bplus/setup_sd.sh`, but don't want to commit before it's tested:

```
#!/bin/sh
# Distro: Void Linux
# Platform: Raspberry Pi 3BPlus
# Boot Media: SD Card


[ -z "$PI_VOID_3BPLUS_SD" ] && echo "'PI_VOID_3BPLUS_SD' must be exported to the boot media device path, exiting..." && exit 1;
PIDRIVE=$PI_VOID_3BPLUS_SD;
PIDRIVEP1=$PIDRIVE'1';
PIDRIVEP2=$PIDRIVE'2';

PIVER='3';
LIBC='-musl'; # '' for glibc, '-musl' for musl
IMGDATE='20181111'; # set this to a more recent image if you want
URL='https://alpha.de.repo.voidlinux.org/live/current/';
IMG="void-rpi$PIVER$LIBC-PLATFORMFS-$IMGDATE.tar.xz";
if [ ! -f "$IMG" ]; then
	echo 'grab image...';
	wget "$URL$IMG";
fi;

echo 'making partitions...';
sudo parted -s $PIDRIVE 'mklabel msdos';
sudo parted -s $PIDRIVE 'mkpart primary fat32 2048s 256MB';
sudo parted -s $PIDRIVE 'toggle 1 boot';
sudo parted -s $PIDRIVE 'mkpart primary ext4 256MB -1';

echo 'making filesystem...';
sudo mkfs.vfat $PIDRIVEP1;
yes | sudo mkfs.ext4 -O '^has_journal' $PIDRIVEP2;

echo 'mounting...';
sudo mkdir rootfs;
sudo mount $PIDRIVEP2 rootfs/;
sudo mkdir rootfs/boot;
sudo mount $PIDRIVEP1 rootfs/boot/;

echo 'unpacking...';
sudo tar xvfJp "$IMG" -C rootfs/ > '/dev/null' && sync;

PIBOOT='/dev/mmcblk0';
PIBOOTP1=$PIBOOT'p1';
PIBOOTP2=$PIBOOT'p2';

echo 'adding boot entry...';
echo "$PIBOOTP1 /boot vfat defaults 0 0" | sudo tee -a rootfs/etc/fstab;

echo 'adding boot options...';
echo '
# Enable audio
dtparam=audio=on
' | sudo tee -a rootfs/boot/config.txt;

echo 'cleanup...';
sudo umount $PIDRIVEP1;
sudo umount $PIDRIVEP2;
sudo rm -rf rootfs/;
```

**Comment by efe3535** [comment]
That was what I exactly did, first I kept the /dev/sdc but after the fstab error, I had to change the fstab. Thanks for your concern :)

**Comment by kpa28-git** [comment]
Cool! I'll add it for future use. :+1: 
Last thing if you want to use the latest image you can change IMGDATE to '20210930', that way you don't have to do a huge update after setting up the sd card. In the future I gotta set it to get the latest image automatically instead of hardcoding :)

**Pull request closed without merging**
